(import :poo-flow/src/module-system/contribution/interface
        :lambda-episteme/governance/objects
        (only-in :std/srfi/1 every delete-duplicates))
(import :lambda-episteme/modules/sdlc/types :lambda-episteme/modules/sdlc/objects)
(export sdlc-with-standards sdlc-module)
(def (sdlc-with-standards profile-value standard-values)
  (unless (and (sdlc-profile? profile-value)
               (list? standard-values) (every standard-profile? standard-values))
    (error "invalid SDLC standard selection"))
  (let ((identities (map (lambda (standard) (.ref standard 'identity)) standard-values)))
    (unless (= (length identities) (length (delete-duplicates identities equal?)))
      (error "duplicate SDLC standard identity")))
  (.o (:: @ profile-value) standards: standard-values))
(def sdlc-module (governance-module SdlcProfile))

(import (only-in :std/srfi/1 any filter find))
(export sdlc-trace-review)
(def (trace-bound? value project)
  (every (lambda (slot) (equal? (.ref value slot) (.ref project slot))) '(subject revision scope)))
(def (unique-identities? values)
  (let ((ids (map (lambda (v) (.ref v 'identity)) values)))
    (= (length ids) (length (delete-duplicates ids equal?)))))
(def (sdlc-trace-review project rule nodes edges)
  (unless (and (sdlc-project? project) (sdlc-trace-rule? rule)
               (list? nodes) (every sdlc-trace-node? nodes) (unique-identities? nodes)
               (list? edges) (every sdlc-trace-edge? edges) (unique-identities? edges))
    (error "invalid or ambiguous trace inventory"))
  (let* ((current-nodes (filter (lambda (n) (trace-bound? n project)) nodes))
         (selected (filter (lambda (e) (and (trace-bound? e project)
                                            (equal? (.ref e 'relation) (.ref rule 'identity)))) edges))
         (of-kind (lambda (category) (filter (lambda (n) (eq? (.ref n 'category) category)) current-nodes)))
         (sources (of-kind (.ref rule 'source-category)))
         (targets (of-kind (.ref rule 'target-category)))
         (endpoint? (lambda (id values) (any (lambda (n) (equal? (.ref n 'identity) id)) values)))
         (valid-edges (filter (lambda (e) (and (endpoint? (.ref e 'source) sources)
                                              (endpoint? (.ref e 'target) targets))) selected))
         (unresolved-edge-values (filter (lambda (e) (not (memq e valid-edges))) selected))
         (unlinked (lambda (values slot)
                     (map (lambda (n) (.ref n 'identity))
                          (filter (lambda (n) (not (any (lambda (e)
                                                         (equal? (.ref e slot) (.ref n 'identity))) valid-edges))) values))))
         (forward (unlinked sources 'source))
         (backward (unlinked targets 'target))
         (status-value (cond ((and (.ref project 'complete?) (pair? unresolved-edge-values)) 'invalid-endpoints)
                             ((not (.ref project 'complete?)) 'unknown)
                             ((or (null? sources) (null? targets)) 'inventory-review-required)
                             ((or (pair? forward) (pair? backward)) 'trace-gaps)
                             (else 'trace-evidence-present))))
    (.o kind: 'sdlc.trace-review status: status-value
        relation: (.ref rule 'identity) subject: (.ref project 'subject)
        revision: (.ref project 'revision) scope: (.ref project 'scope)
        missing-forward: forward missing-backward: backward
        invalid-edges: (if (.ref project 'complete?)
                        (map (lambda (e) (.ref e 'identity)) unresolved-edge-values) '())
        unresolved-edges: (if (.ref project 'complete?) '()
                           (map (lambda (e) (.ref e 'identity)) unresolved-edge-values))
        witnesses: (map (lambda (e) (.ref e 'identity)) valid-edges)
        excluded-nodes: (- (length nodes) (length current-nodes))
        excluded-edges: (- (length edges) (length selected))
        compliance: 'not-evaluated runtime-executed?: #f)))
