MATCH (document:Document)-[reference:REFERENCES]->(decision:Decision)
WHERE decision.status = 'superseded' OR decision.status = 'deprecated'
RETURN document.id, reference.id, decision.id, decision.status
