;;; Render the executable ledger; no separately maintained requirement table.
(import :poo-flow/src/module-system/contribution/interface
        :poo-flow/lambda-episteme/modules/sdlc/standards/nasa-coverage)
(def (main . args)
  (display "#+title: NASA implementation coverage ledger\n\n")
  (display "Generated by =gxi tools/nasa-implementation-report.ss=.\n")
  (display "Rule implementation completeness does not establish project compliance or NASA certification.\n")
  (display "External references are a curated discovery index, not a complete transitive standards closure.\n\n")
  (let (summary (nasa-implementation-summary))
    (display "Implementation complete: =")
    (display (.ref summary 'implementation-complete?))
    (display "=; implemented requirements: =")
    (display (.ref summary 'implemented-count))
    (display "/") (display (.ref summary 'requirement-count))
    (display "=; project compliance: =")
    (display (.ref summary 'project-compliance))
    (display "=; certification: =")
    (display (.ref summary 'certification)) (display "=.\n\n"))
  (display "| Requirement | Paragraphs | Applicability | Validator | Stage inventory | Implementation | Compliance | External dependency | External references |\n|---+---+---+---+---+---+---+---+---|\n")
  (for-each
   (lambda (row)
     (display "| [[") (display (.ref row 'source-url)) (display "][")
     (display (.ref row 'requirement)) (display "]]")
     (for-each (lambda (slot) (display " | ") (display (.ref row slot)))
               '(paragraph-count applicability validator stage-inventory-check
                 implementation-status compliance-status
                 external-reference-status external-references))
     (display " |\n"))
   (nasa-implementation-matrix)))
